name: "hello world"
description: This is a sample YAML file.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:      
  yaml_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to production
        run: echo "Deploying to production..."
