name: CI Workflow

on: push   # <-- Event that triggers workflow

jobs:
  build:   # Job name
    runs-on: ubuntu-latest   # Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
